### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by macjabeth** [invicnaper/spotify-dl#11]
```
[+]  getting track name                                                                                                     
[+] name is If By Chance                                                                                                    
[+] downloading song ..                                                                                                     
WARNING: unable to extract uploader nickname                                                                                
ERROR: Signature extraction failed: Traceback (most recent call last):                                                      
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature                   
    video_id, player_url, s                                                                                                 
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function           
    raise ExtractorError('Cannot identify player %r' % player_url)                                                          
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflOdyxa4/en_US/base.js'; 
please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/updat
e  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.                    
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflOdyxa4/en_US/base.js'; pleas
e report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on
 how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this 
issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update
. Be sure to call youtube-dl with the --verbose flag and include its complete output.                                       
[+] Song Downloaded
```
I'm getting this error when trying to download any song.

**Comment by invicnaper** [comment]
It's a youtube-dl bug, the solution is in the error message

**Comment by WatsOne** [comment]
same bug
