### ISSUE TITLE
Value error while try to dl song

### ISSUE THREAD

**Issue by UgurcanAkkok** [invicnaper/spotify-dl#17]
I have changed first line to use python2 ( #!/usr/bin/python2)
I tried to execute the given command in README,
`./spotify-dl.py --track 4ptmLgM6fPGt79FGLiXEDp --dl youtube`

it gives me this error:
```
Traceback (most recent call last):
  File "./spotify-dl.py", line 9, in <module>
    from bs4 import BeautifulSoup
  File "/usr/lib/python3.7/site-packages/bs4/__init__.py", line 36, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python3.7/site-packages/bs4/builder/__init__.py", line 7, in <module>
    from bs4.element import (
  File "/usr/lib/python3.7/site-packages/bs4/element.py", line 13, in <module>
    from bs4.dammit import EntitySubstitution
  File "/usr/lib/python3.7/site-packages/bs4/dammit.py", line 53, in <module>
    class EntitySubstitution(object):
  File "/usr/lib/python3.7/site-packages/bs4/dammit.py", line 74, in EntitySubstitution
    CHARACTER_TO_HTML_ENTITY_RE) = _populate_class_variables()
  File "/usr/lib/python3.7/site-packages/bs4/dammit.py", line 62, in _populate_class_variables
    character = chr(codepoint)
ValueError: chr() arg not in range(256)
```

**Comment by UgurcanAkkok** [comment]
it turns out it was about my bs4 install, sorry for distrupting but i dont know why it does that
